import Head from 'next/head'
import Image from 'next/image'
import Navbar from 'components/Navbar'
import Layout from 'layout/layout'
import AboutMe from './AboutMe'
import Skills from './Skills'
import Hobbies from './Hobbies'
import Hero from './Hero'
import ContactMe from './ContactMe'


export default function Home() {
  return (
    <>
    <Layout>
      <Head>
        <title>Adrian Karuna Soetikno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
      <Hero/>
      <AboutMe/>
      <Hobbies/>
      <Skills/>
      <ContactMe/>
      
      </main>
    </Layout>
    </>
  )
}
